### ISSUE TITLE
Adsense click does not take action

### ISSUE THREAD

**Issue by emrexhepi** [finalclap/iframeTracker-jquery#10]
Hi i really love this plugin how it works and the idea of how it takes care of the problem but there is a little problem which it is not with other iframes but the google adsense.

My code is like this:
$('#ads iframe').iframeTracker({
        blurCallback: function(){
            // Do something when the iframe is clicked (like firing an XHR request)
			$.cookie.json = true;
			$.cookie('ads', 'clicked', { expires: 2, path: '/' });
        }
    });

This does not save the cookie when i click in iframe I tried the same with the youtube player when I click play it does work just not with the google adsense iframe. Is there something that I'm missing ?

**Comment by finalclap** [comment]
Maybe google adsense uses something like asynchronous loading, so the iframe element is not yet spawned when you set the iframeTracker.
Try wrapping iframeTracker binding inside a timeout function.

Anyway, can you provide a test page ?

**Comment by emrexhepi** [comment]
I can not provide you with a test page sorry, cause of the invalid adsense clicks.
But here is my full code: 

$(document).ready(function() {
	
	var adInterval = setInterval(function(){
		console.log('check');
		if($('#adsense iframe').length == 1) {
			ads_tracker();
			clearInterval(adInterval);
		}
	}, 200);
	
	function ads_tracker() {
		console.log('tracker started');
		console.log($('#adsense iframe'));
		$('#adsense iframe').iframeTracker({
			blurCallback: function(){
				// Do something when the iframe is clicked (like firing an XHR request)
				$.cookie.json = true;
				$.cookie('adsense', 'clicked', { expires: 2, path: '/' });
				alert('adsense clicked');
			}
		});
	}
}); 


console logs:
"check" 
"check" 
"check"
"tracker started" 
Object { 0: <iframe#aswift_0>, length: 1, prevObject: Object, context: HTMLDocument → creativediyideas.com, selector: "#yt_responsive_info iframe" }


When i click on adsense nothing happens neither do the cookies get stored or the alert.

**Comment by finalclap** [comment]
I understand you're scared about sharing your adsense account for test purposes, but I can't help you without a test page.

Google does not provide any kind of sandbox for adsense, but I know a way to get a test page : using Fiddler Autoresponder to mimic google adsense server.
For example :
 1. Create a test page on your computer, containing just just a google adsense ads and iframeTracker trying to tracks clicks on it
 2. Install Fiddler (http://www.telerik.com/fiddler) on your computer, and launch it
 3. Load you test page into your web browser
 4. Go to fiddler, delete all HTTP request not related to google adsense, basically you will end up with something like that :
 
    ```
    http://pagead2.googlesyndication.com/pagead/show_ads.js
    http://www.gstatic.com/pub-config/ca-pub-0000000000000000.js
    http://pagead2.googlesyndication.com/pagead/js/r20150217/r20141212/show_ads_impl.js
    http://googleads.g.doubleclick.net/pagead/html/r20150217/r20141212/zrt_lookup.html
    http://pagead2.googlesyndication.com/pagead/js/r20150217/r20141212/expansion_embed.js
    http://pagead2.googlesyndication.com/pagead/osd.js
    http://googleads.g.doubleclick.net/pagead/ads?client=ca-pub-0000000000000000&output=html...
    ```
 5. Edit adsense GET parameters to remove your account number, use "pub-0000000000000000" as google_ad_client and "0000000000" as google_ad_slot (you can edit a request by right clicking the request : Replay > Reissue and Edit), and delete the original request (containing your true google adsense account id)
 6. Save fiddler session as .saz archive (File > Save > All Sessions), and send me the test page (with fake google_ad_client and google_ad_slot inside google adsense code) and the .saz, so I can load it on fiddler, and use the autoresponder feature without using your google adsense account.

**Comment by emrexhepi** [comment]
Thank you also for the fiddler example. And sorry for the trouble, for some reason now it works perfectly it maybe about the cache or something. But your plugin is very helpful to me keep up the good work. Thank you again :)
